# Generated by Django 6.1 on 2026-08-12 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('dynamicforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('event_name', models.CharField(max_length=150, verbose_name='nombre')),
                ('mode', models.CharField(choices=[('In-person', 'Presencial'), ('Online', 'En línea'), ('Virtual', 'Virtual')], max_length=20, verbose_name='modalidad')),
                ('planned_date', models.DateField(verbose_name='fecha')),
                ('planned_hour', models.TimeField(verbose_name='hora')),
                ('start_datetime', models.DateTimeField(db_index=True, editable=False, verbose_name='inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='fin')),
                ('planned_place', models.CharField(max_length=150, verbose_name='lugar')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('marketing_image', models.CharField(blank=True, max_length=255, verbose_name='imagen')),
                ('visibility', models.CharField(choices=[('Public', 'Público'), ('MembersOnly', 'Solo miembros')], default='Public', max_length=20, verbose_name='visibilidad')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='fecha límite de registro')),
                ('blocked_message', models.CharField(blank=True, help_text='Texto que ve el estudiante cuando el registro está cerrado.', max_length=255, verbose_name='mensaje de bloqueo')),
                ('expected_participants', models.PositiveIntegerField(blank=True, help_text='Solo planificación: no impone tope de inscripciones (RF-33).', null=True, verbose_name='participantes esperados')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club', verbose_name='club')),
                ('registration_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dynamicforms.form', verbose_name='formulario de registro')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAdministrativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('objective', models.TextField(blank=True, verbose_name='objetivo')),
                ('sdg', models.JSONField(blank=True, default=list, help_text='Objetivos de Desarrollo Sostenible.', verbose_name='ODS')),
                ('responsible_task', models.CharField(blank=True, max_length=255, verbose_name='tarea del responsable')),
                ('allies', models.TextField(blank=True, verbose_name='aliados')),
                ('resource_links', models.JSONField(blank=True, default=list, verbose_name='enlaces de recursos')),
                ('impact_measure', models.TextField(blank=True, verbose_name='medición de impacto')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_data', to='events.event', verbose_name='evento')),
                ('responsible_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_events', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'datos administrativos del evento',
                'verbose_name_plural': 'datos administrativos de eventos',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('responses', models.JSONField(default=list, verbose_name='respuestas')),
                ('qr_token', models.CharField(help_text='Opaco y firmado por el servidor. Se valida contra la base, nunca descifrándolo (RNF-05).', max_length=255, unique=True, verbose_name='token QR')),
                ('qr_status', models.CharField(choices=[('Active', 'Activa'), ('Used', 'Usada'), ('Expired', 'Expirada')], default='Active', max_length=10, verbose_name='estado del QR')),
                ('attendance_status', models.CharField(choices=[('Registered', 'Inscrito'), ('Attended', 'Asistió'), ('NoShow', 'No asistió')], default='Registered', max_length=10, verbose_name='asistencia')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='evento')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='dynamicforms.form', verbose_name='formulario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('scanned_at', models.DateTimeField(verbose_name='escaneada el')),
                ('qr_token_validated', models.CharField(max_length=255, verbose_name='token validado')),
                ('status', models.CharField(choices=[('Attended', 'Asistió')], default='Attended', max_length=10, verbose_name='estado')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='evento')),
                ('scanned_by_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to=settings.AUTH_USER_MODEL, verbose_name='escaneada por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='events.eventregistration', verbose_name='inscripción')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='EventStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='asignado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='events.event', verbose_name='evento')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL, verbose_name='miembro')),
            ],
            options={
                'verbose_name': 'staff del evento',
                'verbose_name_plural': 'staff de eventos',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['club', 'start_datetime'], name='idx_event_club_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility'], name='idx_event_visibility'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='chk_event_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'attendance_status'], name='idx_reg_event_attendance'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['qr_status'], name='idx_reg_qr_status'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'student'), name='uniq_event_registration'),
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'student'), name='uniq_event_attendance'),
        ),
        migrations.AddConstraint(
            model_name='eventstaff',
            constraint=models.UniqueConstraint(fields=('event', 'student'), name='uniq_event_staff'),
        ),
    ]
