# Generated by Django 6.1 on 2026-08-12 01:56

import apps.accounts.models
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('enrollment', models.CharField(help_text='Matrícula institucional (202311346) o código GBP (GBP-001).', max_length=20, unique=True, verbose_name='matrícula')),
                ('first_name', models.CharField(max_length=80, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=80, verbose_name='apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[core.validators.validate_espol_email], verbose_name='correo institucional')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[core.validators.validate_not_future_date], verbose_name='fecha de nacimiento')),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semestre')),
                ('career', models.CharField(blank=True, max_length=120, verbose_name='carrera')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('skills', models.JSONField(blank=True, default=list, validators=[core.validators.validate_string_list], verbose_name='habilidades')),
                ('social_media', models.JSONField(blank=True, default=list, help_text='Lista de objetos {"network": "GitHub", "link": "https://..."}.', validators=[core.validators.validate_social_media], verbose_name='redes sociales')),
                ('is_gbp_admin', models.BooleanField(default=False, help_text='Perfil institucional. Se provisiona manualmente (PPD-02); nunca por auto-registro.', verbose_name='administrador GBP')),
                ('is_verified', models.BooleanField(default=False, help_text='RF-01: se activa al seguir el enlace enviado por correo.', verbose_name='correo verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='cuenta habilitada')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al admin de Django')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='catalogs.faculty', verbose_name='facultad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='idx_student_name')],
            },
            managers=[
                ('objects', apps.accounts.models.StudentManager()),
            ],
        ),
    ]
