# Generated by Django 6.1 on 2026-08-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('form_type', models.CharField(choices=[('Membership', 'Membresía'), ('Event', 'Evento')], max_length=20, verbose_name='tipo')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('fields', models.JSONField(default=list, help_text='Esquema del formulario. Ver apps.dynamicforms.schema.', verbose_name='campos')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('is_active', models.BooleanField(default=True, help_text='Solo una versión de cada familia está vigente a la vez.', verbose_name='vigente')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='clubs.club', verbose_name='club')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dynamicforms.form', verbose_name='formulario original')),
            ],
            options={
                'verbose_name': 'formulario',
                'verbose_name_plural': 'formularios',
                'ordering': ['club', 'form_type', '-version'],
                'indexes': [models.Index(fields=['club', 'form_type', 'is_active'], name='idx_form_lookup')],
                'constraints': [models.UniqueConstraint(fields=('root', 'version'), name='uniq_form_version_per_family')],
            },
        ),
    ]
