# Generated by Django 6.1 on 2026-08-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Las entradas no vigentes dejan de ofrecerse en los formularios, pero siguen siendo legibles en los datos históricos.', verbose_name='vigente')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('code', models.CharField(help_text='Sigla institucional, por ejemplo FIEC.', max_length=20, unique=True, verbose_name='sigla')),
            ],
            options={
                'verbose_name': 'facultad',
                'verbose_name_plural': 'facultades',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Las entradas no vigentes dejan de ofrecerse en los formularios, pero siguen siendo legibles en los datos históricos.', verbose_name='vigente')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'área de interés',
                'verbose_name_plural': 'áreas de interés',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
    ]
