# Generated by Django 6.1 on 2026-08-12 02:16

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('catalogs', '0002_seed_catalogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('acronym', models.CharField(max_length=30, verbose_name='acrónimo')),
                ('description', models.TextField(verbose_name='descripción')),
                ('location', models.CharField(max_length=120, verbose_name='ubicación')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='portada')),
                ('leader_enrollment', models.CharField(blank=True, db_index=True, help_text='Matrícula designada por GBP. Puede no tener cuenta aún.', max_length=20, verbose_name='matrícula del líder')),
                ('status', models.CharField(choices=[('Active', 'Activo'), ('Pending Leader', 'Sin líder')], default='Pending Leader', max_length=20, verbose_name='estado')),
                ('social_media', models.JSONField(blank=True, default=list, validators=[core.validators.validate_social_media], verbose_name='redes sociales')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='catalogs.faculty', verbose_name='facultad')),
                ('interest_areas', models.ManyToManyField(blank=True, related_name='clubs', to='catalogs.interestarea', verbose_name='áreas de interés')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_club', to=settings.AUTH_USER_MODEL, verbose_name='líder')),
            ],
            options={
                'verbose_name': 'club',
                'verbose_name_plural': 'clubes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('file', models.FileField(upload_to='clubs/docs/', validators=[core.validators.validate_pdf_file], verbose_name='archivo')),
                ('is_public', models.BooleanField(default=False, help_text='Público: visible para toda la comunidad. Privado: solo para los miembros del club (RF-16).', verbose_name='público')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clubs.club', verbose_name='club')),
            ],
            options={
                'verbose_name': 'documento del club',
                'verbose_name_plural': 'documentos del club',
                'ordering': ['club', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('role_name', models.CharField(max_length=80, verbose_name='nombre del rol')),
                ('is_default', models.BooleanField(default=False, help_text='Los cuatro roles creados con el club. No se pueden borrar.', verbose_name='predeterminado')),
                ('is_leadership', models.BooleanField(default=False, help_text='Solo los roles directivos pueden asignar roles y permisos (RN-7).', verbose_name='directivo')),
                ('is_active', models.BooleanField(default=True, help_text='Decisión D-13: un rol que ya tuvo miembros no se borra, se desactiva, para que las membresías históricas sigan siendo legibles.', verbose_name='vigente')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Diccionario {clave: bool}. Una clave ausente vale False.', verbose_name='permisos')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='clubs.club', verbose_name='club')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['club', '-is_leadership', 'role_name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('valid_from', models.DateField(verbose_name='vigente desde')),
                ('valid_until', models.DateField(verbose_name='vigente hasta')),
                ('status', models.CharField(choices=[('Active', 'Activa'), ('Frozen', 'Congelada'), ('Expired', 'Expirada'), ('Revoked', 'Revocada')], default='Active', max_length=10, verbose_name='estado')),
                ('origin', models.CharField(choices=[('Application', 'Solicitud aprobada'), ('Renewal', 'Renovación de nómina'), ('LeaderAssignment', 'Asignación de liderazgo por GBP'), ('Seed', 'Carga inicial')], default='Application', max_length=20, verbose_name='origen')),
                ('is_leadership', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='es directiva')),
                ('leadership_lock', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('is_leadership', True), ('status', 'Active')), then=models.F('student')), default=None, output_field=models.BigIntegerField(null=True)), output_field=models.BigIntegerField(null=True), verbose_name='cerrojo de liderazgo')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club', verbose_name='club')),
                ('pao_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='academic.paoperiod', verbose_name='período')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='clubs.role', verbose_name='rol')),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
                'ordering': ['-pao_period__sequence', 'club', 'student'],
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['status'], name='idx_club_status'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['faculty', 'status'], name='idx_club_faculty_status'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('leader__isnull', False), ('status', 'Active')), models.Q(('leader__isnull', True), ('status', 'Pending Leader')), _connector='OR'), name='chk_club_status_matches_leader'),
        ),
        migrations.AddIndex(
            model_name='clubdocument',
            index=models.Index(fields=['club', 'is_public'], name='idx_doc_club_public'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('club', 'role_name'), name='uniq_role_per_club'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['club', 'status'], name='idx_membership_club_status'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['student', 'status'], name='idx_membership_student_status'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('student', 'club', 'pao_period'), name='uniq_membership_per_pao'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('leadership_lock',), name='uniq_active_leadership_per_student'),
        ),
    ]
