# Generated by Django 6.1 on 2026-08-12 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaoPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('pao_period', models.CharField(help_text='Identificador del período, por ejemplo 2026-I.', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_pao_format', message='El identificador debe tener la forma AAAA-I o AAAA-II (por ejemplo 2026-I).', regex='^\\d{4}-(I|II)$')], verbose_name='período')),
                ('sequence', models.PositiveIntegerField(editable=False, help_text='Derivado del identificador. 2026-I → 20261.', unique=True, verbose_name='orden cronológico')),
                ('start_date', models.DateField(verbose_name='inicio')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('status', models.CharField(choices=[('Active', 'Activo'), ('Closed', 'Cerrado')], default='Closed', max_length=10, verbose_name='estado')),
                ('active_lock', models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='Active', then=models.Value(1)), default=None, output_field=models.PositiveSmallIntegerField(null=True)), output_field=models.PositiveSmallIntegerField(null=True), verbose_name='cerrojo de período activo')),
            ],
            options={
                'verbose_name': 'período académico',
                'verbose_name_plural': 'períodos académicos',
                'ordering': ['-sequence'],
                'constraints': [models.UniqueConstraint(fields=('active_lock',), name='uniq_single_active_pao'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='chk_pao_end_after_start')],
            },
        ),
    ]
