# Generated by Django 6.1 on 2026-08-12 12:10

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GbpDocumentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('document_type', models.CharField(help_text='Por ejemplo: Nómina de Miembros.', max_length=120, verbose_name='tipo de documento')),
                ('file', models.FileField(upload_to='gbp/processes/', validators=[core.validators.validate_pdf_file], verbose_name='archivo')),
                ('status', models.CharField(choices=[('Submitted', 'Enviado'), ('Under Review', 'En revisión'), ('Approved', 'Aprobado'), ('Rejected', 'Rechazado')], default='Submitted', max_length=20, verbose_name='estado')),
                ('review_feedback', models.TextField(blank=True, help_text='Obligatorias al rechazar (RN-5).', verbose_name='observaciones')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisado el')),
                ('roster_snapshot', models.JSONField(blank=True, default=list, help_text='Evidencia inmutable de la nómina al momento del envío.', verbose_name='nómina congelada')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_processes', to='clubs.club', verbose_name='club')),
                ('pao_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gbp_processes', to='academic.paoperiod', verbose_name='período')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_processes', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_processes', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'trámite GBP',
                'verbose_name_plural': 'trámites GBP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_process_status'), models.Index(fields=['club', 'pao_period'], name='idx_process_club_pao')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'Rejected'), _negated=True), models.Q(('review_feedback', ''), _negated=True), _connector='OR'), name='chk_process_rejection_requires_feedback')],
            },
        ),
    ]
