# Generated by Django 6.1 on 2026-08-12 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('dynamicforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('responses', models.JSONField(default=list, help_text='Lista [{field_id, answer}] validada contra el esquema.', verbose_name='respuestas')),
                ('status', models.CharField(choices=[('Pending', 'Pendiente'), ('Approved', 'Aprobada'), ('Rejected', 'Rechazada')], default='Pending', max_length=10, verbose_name='estado')),
                ('leader_feedback', models.TextField(blank=True, help_text='Obligatoria al rechazar (RN-5).', verbose_name='retroalimentación')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelta el')),
                ('pending_student', models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='Pending', then=models.F('student')), default=None, output_field=models.BigIntegerField(null=True)), output_field=models.BigIntegerField(null=True), verbose_name='cerrojo de postulación (estudiante)')),
                ('pending_club', models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='Pending', then=models.F('club')), default=None, output_field=models.BigIntegerField(null=True)), output_field=models.BigIntegerField(null=True), verbose_name='cerrojo de postulación (club)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clubs.club', verbose_name='club')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='dynamicforms.form', verbose_name='formulario')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_applications', to=settings.AUTH_USER_MODEL, verbose_name='resuelta por')),
                ('resulting_membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='clubs.membership', verbose_name='membresía creada')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'solicitud de membresía',
                'verbose_name_plural': 'solicitudes de membresía',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['club', 'status'], name='idx_application_club_status'), models.Index(fields=['student', 'status'], name='idx_application_student_status')],
                'constraints': [models.UniqueConstraint(fields=('pending_student', 'pending_club'), name='uniq_pending_application_per_club'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'Rejected'), _negated=True), models.Q(('leader_feedback', ''), _negated=True), _connector='OR'), name='chk_rejection_requires_feedback')],
            },
        ),
    ]
