# Generated by Django 6.1 on 2026-08-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado el')),
                ('type', models.CharField(choices=[('application_pending', 'Solicitud recibida'), ('application_approved', 'Solicitud aprobada'), ('application_rejected', 'Solicitud rechazada'), ('membership_revoked', 'Membresía revocada'), ('membership_renewed', 'Membresía renovada'), ('membership_frozen', 'Membresía congelada'), ('leader_assigned', 'Liderazgo asignado'), ('leader_revoked', 'Liderazgo revocado'), ('event_registered', 'Inscripción a evento'), ('attendance_registered', 'Asistencia registrada'), ('gbp_review', 'Trámite por revisar'), ('gbp_resolution', 'Resolución de GBP')], max_length=60, verbose_name='tipo')),
                ('message', models.TextField(help_text='Texto ya renderizado en español: la notificación es presentación, y ahí es donde vive la traducción (RNF-10).', verbose_name='mensaje')),
                ('read', models.BooleanField(default=False, verbose_name='leída')),
                ('target_type', models.CharField(blank=True, max_length=60, verbose_name='tipo de objeto')),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='id del objeto')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clubs.club', verbose_name='club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='idx_notification_user_read')],
                'constraints': [models.UniqueConstraint(fields=('user', 'type', 'target_type', 'target_id'), name='uniq_notification_per_target')],
            },
        ),
    ]
